apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFNU1URXlNekF3TXpBeE5Wb1hEVEk1TVRFeU1EQXdNekF4TlZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTk5SClE0UGFiM1UyMXNsMHBpY0k4YTV3bEtuaWJNcW1JS2grdW1uWHF6aUpnVnlJbmluK3I4TWkvUGgwL0FmbXIzbWgKVjZOSUJjWkg2QXdwTDl6YjI0VVdubk1mbUYzZXJOclFxWWI2TnF4T1Q4QWt0WndibDd3Rko3NnZZdTdlSDNUYQpBQ3RTbXVlQ0lLVTlrNE1iN1poL2wycEZOTUcrNGRqOS9NTTJMQ3lEUlFhTDNJbXZlZGNHa3RxeUhHVTdTbDdSCmY2QlJ2blpta1VhSnF5MWp1S0lZL2h6MWo5TlJYcUpNNVlSY2oyejliQ3N3MDV1YThQTFNpYlVIT1JreU96UDcKcjdkVVFoQ295NEprVmVtSDBWSmtoTUVJTUhTRGp2cjJpV0lWT0wyeEVKdHhmaW9mNndrZGhNcjhCUU9sWCtVWApQZXFTRFNLNkhMZGc0bHpOVktzQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFCWTVSeUpidGFwQ1NZQXl2SGVPR09RdlE0cUgKdHdHdE91blFMT0Z0c1Rya0dPVUZNalZ3L2FCQzJETnI2WFljTVhCSnhPUEtQNjBRQmFhQ3BMNVJJcEd0ZWFTSwp3Z293QWNBSFlMaHcyWkRFOW5uVzdvbERtbUpCVEk3dUowN01hRDRDUUlMTUtQYlRNOW9tUXUwWDFUQXlkMXhYCksxSmhHR0pyZ0x1QU9OUUh3T3FKMmtMTkttN2taV21kck1UNC81NDBsdDJ5WFdiY2RDVldvaFNuTFVKL1NkeUQKcHdnYWloaUc2OU5IUU1Fcm5lWWVwUkFWd2J4N010T0NDeDROMU9ranVEVTQ5SkZRcVBlNnZSRGVjNkNLVHY1Rwo2N283WGZOd3BiWWVqeVYrMHpLWi8zMGM4dGk0TzRqWGcyVGN0d2FDbFE3UFZrZTh5Q2JEakV0Ukd6UT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://29CF6A0A53662B731BFB687DF87AADD1.yl4.us-east-1.eks.amazonaws.com
  name: dev
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFNU1USXdNakF3TXpFMU9Gb1hEVEk1TVRFeU9UQXdNekUxT0Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTVZNCkZUS1pCSTZrNm1aeldvbFlqMVZSTEdQV3RWaTh1bU5XcVVRSXlwZ0djNTVnMkEvTEFZR2tkQ3kvbnNYNXBuM2sKbmUxd25JY2g3K3Yva0Q4Tm1sdW51Z3MvcFhLcGQ3ZzdnOEpmampXYzVpbDQ2Z2RSWG1UVEVxNzU5dStFb1JuZgpzMGUrbnF2elRBN2xkcEFNRlZaeW1lMG5weHBxbG85cCtVa2NMWlZpRnhLTko3VjJnWjVycm85dEVMTVozWXVBCk1ncWRxRjYycmxWNnlqekM2VHZ4SU85eHp3c0RReUJRSVVVOUJ0eUJNc3BLR25pV25iYm5UdzRQWVkxcmc2RW4KeXEzNXU1SUU1REJSS1BLR1NHajVWQ09nemFTWlJYeU16aEFjTzVycVYwdXoxTUZZdjNHVkJlMEhhL2pPMCsyWApKZWlaL1IrNng1aXErcVhOMFlrQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFGRDFIdndZdHBPc2pyWGQvMEdZOS9pRGw1bFMKL3F2WWQveU1kWXR3cHp3UDZOdzJ0Z1FCRlJqM3VXZlBpUVYwZzhSaHV0NzE4Z05BMUlvTm5JTEJKYm5zaEN1OQpFc01nZXNYODhYeGFCNjhYMXVtZG9PRkU0YlhrU2g3WWd0T05IZlpBRmlOMDVJbGZTQmRzOUZib2VseEZEMUIwCnNSYlBqOGZKZVA4YVFqd3dubVVxZC96bHdaRXlkcWlsNUNhdmtNL2krRXI4ODBUTFF1enZ2Yk13T0NjQWh3OHoKYzhQRHQyYmpvc054eTRDaGlsRkNiRmFPSzlYZ1hXYTBtS1duV2xSN2NDTU1HRDlUNTVCZ2hITDM0Z1oybzRNTgpFQVkzMitNSGdQdyt2a0kvNDZOVm1PbGxmYTJvamxLbkFYUFNtSENhNHVPUWIvL0hENUJXOGhCekV4Yz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://FA252FCD5E123F6FDA25920AE64DDCA9.gr7.us-east-1.eks.amazonaws.com
  name: impl
contexts:
- context:
    cluster: impl
    user: impl
  name: impl
- context:
    cluster: dev
    user: dev
  name: dev
kind: Config
preferences: {}
users:
- name: impl
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - fhir-impl-eks
      - arn:aws:iam::214843959152:role/impl-eks-master-NodeInstanceRole-2ILZ7L46L6LU
      command: aws-iam-authenticator
- name: dev
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - fhir-dev-eks
      - arn:aws:iam::214843959152:role/impl-eks-master-NodeInstanceRole-2ILZ7L46L6LU
      command: aws-iam-authenticator
current-context: impl
