---
# DEPLOYMENT MANIFEST #
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fhir-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fhir
  template:
    metadata:
      labels:
        app: fhir
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: fhir-image
        image: semqam/fhir:latest  # docker image
        ports:
        - containerPort: 8080
        resources: {}
        env:
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: fhir-secret
                key: DB_HOST
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: fhir-secret
                key: DB_PORT
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: fhir-secret
                key: DB_NAME
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: fhir-secret
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: fhir-secret
                key: DB_PASSWORD
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: fhir-secret
                key: DB_USER
          - name: APP_URL
            valueFrom:
              secretKeyRef:
                name: fhir-secret
                key: APP_URL

---
# SERVICE MANIFEST #
apiVersion: v1
kind: Service
metadata:
  name: fhir-service
  labels:
    app: fhir
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: fhir
  sessionAffinity: None
  type: ClusterIP
